[default]

THREADS_PER_PAGE = 2

CSRF_ENABLED = "True"
WTF_CSRF_CHECK_DEFAULT = "True"

SQLALCHEMY_TRACK_MODIFICATIONS = "True"

WEBPACKEXT_MANIFEST_PATH = "manifest.json"

SECURITY_TRACKABLE = "True"
SECURITY_REGISTERABLE = "False"
SECURITY_PASSWORD_HASH = "bcrypt"
SECURITY_POST_LOGIN_VIEW = "/dashboard"
SECURITY_UNAUTHORIZED_VIEW = "/login"
SECURITY_LOGIN_USER_TEMPLATE = "security/login.jinja"

# FLASK_ADMIN_SWATCH= 'flaty'

SUPERVISOR_USER_HOME = "{supervisor_path}/programs/{username}"

[production]

SQLALCHEMY_DATABASE_URI = "postgresql://hosting:<hostingpassword>@localhost/hostingapp"

SECRET_KEY = "YMNx&VZ<:85#=61_dUr\\x0b*)vL"
SECURITY_PASSWORD_SALT = "YMNx&VZ<:85#=61_dUr\\x0b*)vL"

SERVER_NAME = "localhost:5000"

SUPERVISOR_CONFIG_DIR = "/var/www/hosting/supervisor"
SUPERVISOR_PROGRAM_TEMPLATE_PATH = "/var/www/hosting/conf_templates/subprogram_template.ini"

UWSGI_TEMPLATE_PATH = "/var/www/hosting/conf_templates/uwsgi_template.ini"
ABS_PATH_HOME_UWSGI = "/home/aurel"  # should change on production

FIREJAIL_PROFILE = "/var/www/hosting/conf_templates/default.profile"

FTP_PORT = 2121
FTP_HOST = "ftp://localhost"
FTP_BASE_DIR = "/var/www/hosting/ftpfiles"

NGINX_PID_FILE = "/run/nginx.pid"
NGINX_SITE_CONF = "/var/www/hosting/nginx/sites-enabled"
NGINX_HUP_CHECK_FILE = "/tmp/.send_hup_to_nginx"
NGINX_CONF_TEMPLATE_PATH = "/var/www/hosting/conf_templates/virtual_host_nginx.site.conf"


[developement]

# SQLALCHEMY_DATABASE_URI = "sqlite:///./var/data.db"
SQLALCHEMY_DATABASE_URI = "postgresql://aurel:shift@localhost/clientapp"

SERVER_NAME = "localhost:5000"

SUPERVISOR_CONFIG_DIR = "./supervisor"
SUPERVISOR_PROGRAM_TEMPLATE_PATH = "./supervisor/subprogram_template.ini"

UWSGI_TEMPLATE_PATH = "./supervisor/uwsgi_template.ini"

FIREJAIL_PROFILE = "./supervisor/default.profile"

NGINX_CONF_TEMPLATE_PATH = "./supervisor/virtual_host_nginx.site.conf"

FTP_PORT = 2121
FTP_HOST = "ftp://localhost"
FTP_BASE_DIR = "/media/aurel/main/projects/self/clientapp/tmp"

ABS_PATH_HOME_UWSGI = "/home/aurel"  # should change on production

NGINX_PID_FILE = "/run/nginx.pid"
NGINX_SITE_CONF = "/var/www/nginx/sites-enabled"
NGINX_HUP_CHECK_FILE = "/tmp/.send_hup_to_nginx"

SECURITY_PASSWORD_SALT = "YMNx&VZ<:85#=61_dUr\\x0b*)vL"

DEBUG_TB_ENABLED="False"
DEBUG_TB_INTERCEPT_REDIRECTS = "False"

# Secret key for signing cookies

SECRET_KEY = "YMNx&VZ<:85#=61_dUr\\x0b*)vL"
